### ISSUE TITLE
Do we need built-in predicates?

### ISSUE THREAD

**Issue by scotttrinh** [prayerslayer/js.spec#10]
Thanks for your hard work in getting this off the ground so far! Looks great!

Out of curiosity, is there any reason you feel like this library needs built-in predicates? It seems to me that the basic building blocks of clojure.spec are specs, regexs (cat, alt, *, etc), data generation and function specs. I know you mentioned JS not having a standard library of predicates like clojure, but I'd argue that that is a good reason to let people bring (or build) their own. The most interesting predicates that make spec valuable beyond a type system are not ones that an easily expressed by a single predicate anyway. Think positive integer, number between, array with a certain length, etc etc.

**Comment by prayerslayer** [comment]
> is there any reason you feel like this library needs built-in predicates

I think you argue correctly that these are not what makes js.spec useful.

However I would like to have a small-ish amount of predicates built in so that js.spec is easier to use and start out with. That would include basic type checking, numbers (positive, nevative with/without zero, number between...) and strings (regex and predefined matchers for email etc.).

In my opinion we get the best of both worlds with this approach: Beginners/curious people can do basic stuff without loading lodash or rolling their own predicates. Everyone else is free to do so if necessary.

**Comment by scotttrinh** [comment]
Cool, I respect that opinion. I feel like users are going to divided on this issue since a lot of JS devs are hyper-modular and don't want the added weight, but, as you said, the benefits to new users may out-weigh those objections. Thanks for the quick feedback!

**Comment by prayerslayer** [comment]
> a lot of JS devs are hyper-modular and don't want the added weight

Yes, I've been on that side of the fence too. But as a matter of fact you satisfy 1 % of developers and make it worse for everyone else.

I guess we could work complaint-driven here and maintain a separate `js.spec-hardcore` package without most of the predicates (some are used internally) :grin:

**Comment by scotttrinh** [comment]
I'd hardly say the pro-tiny-modules camp is 1% of developers, but I get your point. Even if it's something big like 75% of developers, it might *still* be worth the lower barrier to entry.

One way around this, granted it would require work, would be to use ES6 modules and something like `rollup` to publish ES6 modules (and CommonJS) and let people tree-shake out the unused code. You could then, conceivably, use `lodash/es` and then you wouldn't have to create a custom `lodash` build, either.

At any rate, I'm certainly not pushing for it, I just wanted to open up the conversation. 👍
