### ISSUE TITLE
Are custom predicates supported?

### ISSUE THREAD

**Issue by juanjoLenero** [prayerslayer/js.spec#50]
It is not clear from the documentation whether custom predicates are supported and if so, how to create/use them.

**Comment by mattbishop** [comment]
Well you can just pass in a function instead of a predefined predicate. If you look at the docs on predicate you will find several examples: https://prayerslayer.gitbooks.io/js-spec/content/specs.html

You are correct though that this fact isn't clearly stated as it is mixed in with the "Predefined Specs" section examples.

**Comment by mattbishop** [comment]
Actually this is spelled out at the start: https://prayerslayer.gitbooks.io/js-spec/content/concepts.html

**Comment by juanjoLenero** [comment]
I stand corrected, thank you.
